apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: recce

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - ingress.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: recce
      app.kubernetes.io/part-of: recce

images:
  - name: recce
    newName: arunsharma08/recce
    newTag: latest
