apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: recce-web-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: recce
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
